blade_brew_formulae_extra:
  - python@3.11   # ComfyUI
  - git           # ComfyUI
  - cmake         # ComfyUI extensions

blade_brew_casks: []

blade_comfyui_enabled: true
blade_comfyui_download_models: true

blade_ollama_models:
  - "deepseek-r1:70b"
  - "qwen3.5:35b"

blade_ollama_models_dir: "/Volumes/Data/ollama/models"
